Add Tenant(Project) Roles
os-migrate/os-migrate pull request #268
Opened 2020-09-15 16:15 UTC by rbrady

This patch adds the roles and supporting code to import and export
OpenStack projects.

2020-09-16 13:24 UTC, ccamacho reviewed
When you have some time, for the docs is required to add references
here:
  - https://github.com/os-migrate/os-migrate/tree/main/docs/src/roles
and here:
  - https://github.com/os-migrate/os-migrate/tree/main/docs/src/modules

2020-09-16 13:41 UTC, rbrady commented
Thanks for the heads up on docs, I need to add those steps to the contributing doc.

2020-09-17 08:17 UTC, ccamacho commented on os_migrate/roles/export_projects/README.md
> +Please refer to
This should point similar to: https://github.com/os-migrate/os-migrate/pull/270/files#diff-c3d7c71d6d79498900947637e86723ddL2

2020-09-23 08:40 UTC, ccamacho reviewed
For the current CI error, the modules should be included here:
os_migrate/tests/sanity/ignore-2.9.txt

2020-09-24 15:51 UTC, jistr requested changes

2020-09-24 15:51 UTC, jistr commented on os_migrate/plugins/module_utils/project.py
> +        'is_enabled',
`is_enabled` should be a param if the create method supports it.

2020-09-25 11:08 UTC, jistr requested changes

2020-09-25 11:08 UTC, jistr commented on tests/func/run/all.yml
> +  tags: always
Looked at the test results now, yeah this won't run. We'll need to do the split of Makefile targets and auth files and test playbooks between admin and tenant variants. I think we can mirror what was done in e2e tests and it should work.

2020-10-02 14:50 UTC, rbrady commented
still investigating why I get two instances of the seeded project in the test.

2020-10-02 20:53 UTC, rbrady commented
The issue appears to be where the import_project is run in the idempotent test, the project "osm_project" is imported successfully.  The credentials for the test_as_admin are same for src and dest tenants, and the creation of two projects with the same name is allowed in the openstack api.  This causes a case that results in two projects named "osm_project" in the same tenant.  I'm not sure if the best case here is to either create and use a separate admin user for the admin tests (admin-alt) or add the code to artificially restrict creating two projects with the same name.

2020-10-05 15:37 UTC, jistr reviewed
Export idempotence logic seems to be the issue here, it relies on `id` property. We should add a special case for Project resources, for which it should rely on the tuple (domain_id, name), as Projects don't have IDs but they are uniquely named within a domain. The special case can be inserted here:

https://github.com/os-migrate/os-migrate/blob/main/os_migrate/plugins/module_utils/serialization.py#L61-L65

2020-10-06 15:28 UTC, rbrady commented
Added the special case in serialization.py and updated the func tests as needed.

2020-10-07 13:48 UTC, jistr approved these changes
LGTM. I don't think this would influence e2e tests but it's a large patch so i'm adding a CI run just to make sure.

2020-10-07 14:42 UTC, merged