Resource check
os-migrate/os-migrate pull request #283
Opened 2020-10-12 12:50 UTC by rbrady

2020-10-27 10:06 UTC, jistr requested changes
Does this need a rebase on top of the latest main branch? The diff looks like the PR is introducing export/import for projects, but that was already merged earlier. So there's a lot of irrelevant code in the review diff.

2020-10-27 13:12 UTC, rbrady commented
> Does this need a rebase on top of the latest main branch?

Rebased.

2020-11-02 17:31 UTC, jistr requested changes

2020-11-02 17:31 UTC, jistr commented on os_migrate/plugins/module_utils/serialization.py
> +def add_or_replace_resource_old(resources, resource_or_data):
We can delete this `_old` function now, right? The refactored function looks good, and the rest of the patch too. :+1:

2020-11-05 12:18 UTC, jistr approved these changes
Thanks!

2020-11-05 12:18 UTC, merged