Dev: Convert to fully qualified collection names
os-migrate/os-migrate pull request #344
Opened 2021-01-21 15:27 UTC by ccamacho

Starting on Ansible 2.9 all tasks can use
the fully defined collection name the builtin
runtime is specified in:
https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml

2021-01-22 14:41 UTC, ccamacho commented
This is passing the functional tests but be aware that it breaks the workload migrations.

2021-01-25 14:49 UTC, ccamacho commented
Passing all, the breaking change was not related to this PR.

2021-01-26 11:02 UTC, jistr requested changes

2021-01-26 13:13 UTC, ccamacho commented on Makefile
> +	ansible-galaxy collection install -r collection-requirements.yml; \
moved the req files to the galaxy file, commit message updated, merged the pending PRs

2021-01-26 15:05 UTC, jistr approved these changes
Thanks for the updates, LGTM. The last bugfix only edits a .py file constant so it will not conflict, we can merge in any order.

2021-01-26 15:06 UTC, ccamacho commented
Let's re-execute the e2e tests to be sure there are no NITs in the rebase

2021-01-26 15:10 UTC, jistr commented
Yes +1

2021-01-26 17:50 UTC, jistr commented
Something's wrong with OSP 10 cloud it seems, i'll check tomorrow.

2021-01-26 17:50 UTC, jistr commented
The CI on my patch failed too.

2021-01-27 16:57 UTC, merged