Oth: User documentation on the inner workings of workload migration
os-migrate/os-migrate pull request #469
Opened 2021-08-27 11:39 UTC by jistr

Also i'm piggy-backing a Dev commit into the pull request re tagging data seed tasks in tests, which came in handy for demo preparation.

2021-08-31 13:56 UTC, philroche approved these changes
Excellent and nice diagrams too

2021-08-31 14:03 UTC, ccamacho requested changes

2021-08-31 14:40 UTC, jistr commented on docs/src/user/how-it-works-workload-migration.rst
> +.. figure:: https://raw.githubusercontent.com/os-migrate/os-migrate/main/media/walkthrough/2020-06-24-osp-migrate-fig5.png?raw=true
Yes but i'd perhaps do another PR with this? I didn't want to refactor everything until we get the rendering mechanism in place.

2021-08-31 14:42 UTC, ccamacho commented on Makefile
> +	plantuml -tsvg -output render ./docs/src/images/plantuml/*.plantuml
++

2021-08-31 15:53 UTC, jistr commented on Makefile
> +	plantuml -tsvg -output render ./docs/src/images/plantuml/*.plantuml
Done, using DPI 150 for rendering which seems to be alright for the web. Also rebased onto main branch as i wanted both toolbox edits at the same time (using Fedora 34 && the new packages for plantuml).

2021-09-01 06:07 UTC, ccamacho approved these changes

2021-09-01 06:07 UTC, merged