dev: lockfile patch for use_lock process
os-migrate/os-migrate pull request #590
Opened 2023-02-11 23:24 UTC by cloudguruab

This adds a `remove_lockfiles` and `check_process` method to the `use_locks` decorator to handle responses to waiting for lockfile releases within the conversion hosts. https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=16007&view=detail&selectedIssue=OSP-13078&quickFilter=101301

2023-02-23 14:12 UTC, cloudguruab commented
- [ ] add ci patch to separate PR

2023-03-01 08:39 UTC, jistr requested changes

2023-03-06 19:34 UTC, cloudguruab commented
I agree this approach is cleaner, simply handling check/cleanup lockfiles when composing on `126` allows us to utilize check_process against the cleanup_and_check method. Keeps it DRY as well.

2023-03-07 17:07 UTC, jistr requested changes
Two small things but other than that i think it's good to go!

2023-03-07 17:07 UTC, jistr commented on os_migrate/plugins/module_utils/workload_common.py
> +                    check_and_cleanup_lockfiles()
The lock which is being created by this use_lock decorator is cleaned up on line 93 above. It probably won't hurt but if line 93 didn't succeed, i'm not sure if it's worth trying again.

2023-03-09 15:07 UTC, jistr requested changes

2023-03-10 20:24 UTC, cloudguruab commented on os_migrate/plugins/module_utils/workload_common.py
> +            os.remove(lockfile)
I'm testing this, but I think running the check_and_cleanup method only when an error occurs would be better as a routine step.

2023-03-13 02:56 UTC, cloudguruab commented on os_migrate/plugins/module_utils/workload_common.py
> +            os.remove(lockfile)
Was able to clear this up, looks like its searching against other lockfiles in each migration step where the decorator is used. Maybe adding if conditions around the loop could work, but might cause missed failures

2023-03-14 15:35 UTC, merged